# Numpy 

In [1]:
import numpy as np       

## Creating Arrays

* we can create an array
* We can Convert a list into array

In [2]:
arr_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])        # .array(object) ---> create an array
arr_1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
list1 = [1, 2, 3, 4, 5]
print(list1)
print(type(list1))
print('\n')

arr = np.array(list1)    # .array(list) ---> Creating an array from a list
print(type(arr))
print(arr)
arr

[1, 2, 3, 4, 5]
<class 'list'>


<class 'numpy.ndarray'>
[1 2 3 4 5]


array([1, 2, 3, 4, 5])

## Types of Arrays

* 1D
* 2D
* 3D

In [4]:
# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) 

# 3D array
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]]])
print(arr_1d)
print('\n')
print(arr_2d)
print('\n')
print(arr_3d)

[1 2 3 4 5]


[[1 2 3]
 [4 5 6]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
np.arange(10)          # np.arange(stop) ---> create an array of evenly spaced values
                       #                      stop not included
                       #                      Default start is 0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(2,15)        # np.arange(stat, stop)   always start < stop

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
np.arange(0, 100, 5)     # np.arange(start, stop, step) 
                         # step will jump that many of times

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [8]:
np.zeros(5)     # 1D array of 5 float 0's

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((4,5))  # 2D arrays of 4 rows, 5 cloumns of 0's

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(4)      # 1D array of 4 float 1's

array([1., 1., 1., 1.])

In [11]:
np.ones((7,5), dtype = int)   # 2D arrays of 4 rows, 5 cloumns of 0's, dtype ---> will chainge data type

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
np.twos((3,2))   # tow's and three's are not allowed to call in np liberary

AttributeError: module 'numpy' has no attribute 'twos'

In [13]:
np.random.randint(2,17)    # .randint(low, high) ---> returns a randon between low and high but not high

10

In [14]:
np.random.randint(1,10,(4,3)) # .randint(low, high, (row, column))

array([[9, 2, 1],
       [7, 7, 1],
       [9, 5, 4],
       [3, 3, 6]])

In [15]:
np.random.randint(50,100,10)

array([96, 88, 71, 71, 98, 50, 50, 84, 52, 85])

# Operators

In [16]:
arr = np.array([0, 1, 2, 3, 4, 5])
arr

array([0, 1, 2, 3, 4, 5])

In [17]:
print(arr.max())
print(arr.min())
print(arr.mean())

5
0
2.5


In [18]:
from numpy import *
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(median(a))

6.5


In [19]:
a.reshape(4,3)   # .reshape(row, column) ---> Returns an array with same data with a new shape

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

## Indexing

In [21]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [22]:
mat[1:7,1:4]   # It uses indexing and slicing to call a portion of array

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43],
       [51, 52, 53],
       [61, 62, 63]])

## Masking

In [23]:
mat > 50  # Compares element and returns bool matrix

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [24]:
mat[mat<50]     # Filter and extract elements from the array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [25]:
mat[mat>30] 

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
       99])